### ISSUE TITLE
ERT test suite error: undefined function

### ISSUE THREAD

**Issue by spwhitton** [davidshepherd7/frames-only-mode#14]
Test revertable-set-multiple backtrace:
      (let ((lm/foo 1) (lm/bar "a") (lm/revert-fn nil)) (setq lm/revert-fn
      (lambda nil (let ((lm/foo 1) (lm/bar "a") (lm/revert-fn nil)) (setq 
      #[0 "\306\307!r\211q\210\310\311\312\313\314\315!\316\"\317\320%DC
      funcall(#[0 "\306\307!r\211q\210\310\311\312\313\314\315!\316\"\31
      ert--run-test-internal([cl-struct-ert--test-execution-info [cl-struc
      #[0 "r\304 q\210\305 )\306\307\310\311\312\313!\314\"\315\316%DC\2
      funcall(#[0 "r\304 q\210\305 )\306\307\310\311\312\313!\314\"\315\
      ert-run-test([cl-struct-ert-test revertable-set-multiple "" (lambda 
      ert-run-or-rerun-test([cl-struct-ert--stats t [[cl-struct-ert-test a
      ert-run-tests(t #[385 "\306\307\"\203D\211\211G\310U\203\211@\20
      ert-run-tests-batch(nil)
      ert-run-tests-batch-and-exit()
      eval((ert-run-tests-batch-and-exit))
      command-line-1(("-l" "package" "--eval" "(add-to-list 'package-direc
      command-line()
      normal-top-level()
    Test revertable-set-multiple condition:
        (void-function let-mode-revertable-set)
       FAILED  6/8  revertable-set-multiple
    Test revertable-set-set-outside backtrace:
      (let ((lm/foo 1) (lm/revert-fn nil)) (setq lm/revert-fn (let-mode-re
      (lambda nil (let ((lm/foo 1) (lm/revert-fn nil)) (setq lm/revert-fn 
      #[0 "\306\307!r\211q\210\310\311\312\313\314\315!\316\"\317\320%DC
      funcall(#[0 "\306\307!r\211q\210\310\311\312\313\314\315!\316\"\31
      ert--run-test-internal([cl-struct-ert--test-execution-info [cl-struc
      #[0 "r\304 q\210\305 )\306\307\310\311\312\313!\314\"\315\316%DC\2
      funcall(#[0 "r\304 q\210\305 )\306\307\310\311\312\313!\314\"\315\
      ert-run-test([cl-struct-ert-test revertable-set-set-outside "" (lamb
      ert-run-or-rerun-test([cl-struct-ert--stats t [[cl-struct-ert-test a
      ert-run-tests(t #[385 "\306\307\"\203D\211\211G\310U\203\211@\20
      ert-run-tests-batch(nil)
      ert-run-tests-batch-and-exit()
      eval((ert-run-tests-batch-and-exit))
      command-line-1(("-l" "package" "--eval" "(add-to-list 'package-direc
      command-line()
      normal-top-level()
    Test revertable-set-set-outside condition:
        (void-function let-mode-revertable-set)
       FAILED  7/8  revertable-set-set-outside

**Comment by davidshepherd7** [comment]
Thanks! Turns out I wasn't running those tests because ert-runner only runs files with `test` in the filename.
