### ISSUE TITLE
flycheck errors buffer is opened in new frame

### ISSUE THREAD

**Issue by IvanMalison** [davidshepherd7/frames-only-mode#15]
This can be quite annoying if you are simply putting the buffer in an invalid state temporarily as you edit code. There might be a way to supress this built in to flycheck, but this is worth investigating.

**Comment by davidshepherd7** [comment]
Ah yes, I have a setting to display these messages in the minibuffer instead but I forgot to add it to frames-only-mode. I'll add it now.
