### ISSUE TITLE
Consider switching ido-default-buffer-method to 'selected-window

### ISSUE THREAD

**Issue by IvanMalison** [davidshepherd7/frames-only-mode#16]
I think most people using this mode would not want the default behavior, which is to raise any frame that already has the buffer displayed.

**Comment by davidshepherd7** [comment]
Hi, I'm not sure about adding this. 

I imagine that most people would want `'selected-window` because it seems like the sensible setting (if I say open the file here then do it!). But I don't think that it's closely related enough to making frames work nicely to include it here.

**Comment by IvanMalison** [comment]
That's fair, but the thing is that `'selected-window` is indistinguishable from the default, `'raise-frame`, when using emacs in window mode.

**Comment by davidshepherd7** [comment]
Ok, I'll have a play with it and see.

**Comment by davidshepherd7** [comment]
Yeah I see what you mean, I've added that setting. Thanks for the suggestion :+1:
