### ISSUE TITLE
Configurable Frame Focus?

### ISSUE THREAD

**Issue by mekeor** [davidshepherd7/frames-only-mode#17]
I use frames-only-mode in GNU Emacs (26.0.50.6) in XMonad (0.12). Sometimes, when a new Emacs-frame is created by frames-only-mode, the focus of the cursor switches to that new frame while XMonad still focuses the old frame. In particular, for me, this happens every time I invoke `intero-repl-load` (`C-c C-l`) within `haskell-mode` and `intero-mode`. So, my window manager XMonad then focuses a different window than the cursor is typing in. That's quite confusing and disturbing, especially if it happens every time.

Is it possible to ask the window manager to focus the newly created frame instead from within frames-only-mode? If so, I'd suggest a customizable option for frames-only-mode which allows you to either

1. behave as it is behaving right now; or
2. always focus the new frame; or
3. always focus the old frame.

PS: Thank you for this package!

**Comment by davidshepherd7** [comment]
Hi, have you noticed this happening with any other frames? `intero-mode` doesn't seem to be a particularly easy thing to get running.

**Comment by davidshepherd7** [comment]
In fact, it looks like intero-mode is just using [`pop-to-buffer`](https://github.com/commercialhaskell/intero/blob/master/elisp/intero.el#L863) to select the repl buffer, which should work fine with `frames-only-mode` (just tested with my config). 

Could it be something else in your config that's causing the issue? Have you tried reproducing it with `emacs -Q`? If it does turn out to be something in your config have a look for any customisations of the `display-buffer` function (there are quite a few ways of customising it, have a look at the documentation).

**Comment by mekeor** [comment]
Sorry for neglecting this issue. I'll update soon.

**Comment by mekeor** [comment]
I'm closing this until I encounter it again.

**Comment by mekeor** [comment]
I have now also been experiencing this issue with [geiser](https://github.com/jaor/geiser). Soon, I'll see if I can reproduce it and offer more details.
