### ISSUE TITLE
How about Emacs 25? =)

### ISSUE THREAD

**Issue by michalrus** [davidshepherd7/frames-only-mode#19]
Just checked and it works.

Is there anything that still doesn’t work with 25?

**Comment by davidshepherd7** [comment]
Yeah emacs 25 should be fine (it's what I'm using!), have I left an outdated comment somewhere saying it isn't compatible?

**Comment by michalrus** [comment]
Cool! :smiley: 

Just here, I think: https://github.com/davidshepherd7/frames-only-mode/blob/5a2947d797a5d6f74d3a9c97f8c0ab6cff115b28/frames-only-mode.el#L7

But because of that Melpa claims it’s for Emacs 24.

**Comment by davidshepherd7** [comment]
I think that's supposed to be a [minimum version](https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html), the way it appears on melpa is misleading though.

**Comment by michalrus** [comment]
Ah, right! I would’ve expected `>=24.4` or similar. Thanks!
