### ISSUE TITLE
I use `restclient` which pops up temp buffers, can they be in the same window?

### ISSUE THREAD

**Issue by freckletonj** [davidshepherd7/frames-only-mode#20]
I only ask because this seems like a generally applicable problem whose solution would work for many different packages.

When I use `restclient`, it pops up an `*HTTP Response*`, and it'd be nice for that to appear in the same frame.

And if not, that's fine too. I love `frames-only-mode`!!!

**Comment by davidshepherd7** [comment]
Yeah `frames-only-mode-use-window-functions` might do what you need. Something like:

    (add-to-list 'frames-only-mode-use-window-functions 'restclient-http-handle-response)

then toggle `frames-only-mode` off and on again and it should work. In general you just need to find the function which calls `display-buffer` and add it to the list.

**Comment by freckletonj** [comment]
beautiful! thanks for taking the time to even pull out that `restclient...` fn, I'd scoured the docs, but didn't realize this was the answer!

Ah, `frames-only-mode` makes `xmonad` awesome!
