### ISSUE TITLE
eshell and frames-only-mode-use-windows-for-completion

### ISSUE THREAD

**Issue by sj4** [davidshepherd7/frames-only-mode#26]
when using eshell, the frames-only-mode-use-windows-for-completion setting seems to ignored. I'm using the default setting (open completion in Emacs window, not in separate frame) but with eshell, completion is opened in a separate frame, focus is lost, etc.

Would be nice to add eshell as exception somewhere, thanks.

**Comment by davidshepherd7** [comment]
Yeah I didn't have an advice on `pcomplete`, should be fixed now but let me know if it's not (I've not really used eshell so I'm not entirely sure how the completion normally works).

Thanks for letting me know :+1:
