### ISSUE TITLE
Add a `clone-indirect-buffer-other-frame` function here?

### ISSUE THREAD

**Issue by japhir** [davidshepherd7/frames-only-mode#30]
In core emacs, `clone-indirect-buffer-other-window` is bound to `C-x 4 c`. This creates an indirect buffer of the current buffer in a new window. This is quite nice, but with frames-only mode and my tiling wm (sway in my case) I prefer to open it in a new frame. Apparently, many other frame-related keybindings are bundled under `C-x 5`, so I've proposed to add the slightly modified function below to emacs core [here](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=35466), but that didn't get any traction yet. See also the [reddit thread](https://www.reddit.com/r/emacs/comments/bhsa1q/inscrutability_of_cx_4_and_cx_5/elwm1pp/) that sparked this thought. What do you think about adding it here, since it's mostly interesting for frame-people?

```
(defun clone-indirect-buffer-other-frame (newname display-flag &optional norecord)
  "Like `clone-indirect-buffer' but display in another frame."
  (interactive
   (progn
     (if (get major-mode 'no-clone-indirect)
	 (error "Cannot indirectly clone a buffer in %s mode" mode-name))
     (list (if current-prefix-arg
	       (read-buffer "Name of indirect buffer: " (current-buffer)))
	   t)))
  (let ((pop-up-frames t))
    (clone-indirect-buffer newname display-flag norecord)))
```

**Comment by davidshepherd7** [comment]
Sorry, I don't think that's closely related enough to what frames-only-mode aims to do and I'd like to keep the package small so that it's easier to maintain.

I think emacs core is the right place for it to live (alongside other closely related functions).
