### ISSUE TITLE
Frames-only-mode conflict with `org-latex-preview`

### ISSUE THREAD

**Issue by nettoyoussef** [davidshepherd7/frames-only-mode#32]
Hi, thanks for the awesome package!
 I use it all the time.

### Problem

Recently, I am porting my technical writing to Emacs. But I am finding a problem with the function `org-latex-preview`. Without using `frames-only-mode` the function doesn't open a new frame.

However, when `frames-only-mode` is activated, every time a new equation is inserted in a org-mode for the first time, `org-latex-preview` calls `dvipng` which opens a new window with the message:

>"This is dvipng 1.16 Copyright 2002-2015, 2019 Jan-Ake Larsson [1] ".

I tried including the frame that opens in the list  `frames-only-mode-kill-frame-when-buffer-killed-buffer-list`  ("*Org Preview LaTeX Output*"), but the frame still opens.

I also tried to add a hook in `post-command-hooks` and `add-advice`, with the function below, but both didn't work either.

Do you know what can I do? 

```lisp
(defun kill-latex-preview-window ()
  (interactive
  (let ((buffer "*Org Preview LaTeX Output*"))
    (if (get-buffer buffer)
        (progn
        (delete-frame (select-frame-by-name buffer))
        (kill-buffer buffer)
        )
    )
  )
  )
)

(add-hook 'post-command-hook 'kill-latex-preview-window )
```

## Other useful info

* Emacs version: 26.3
* frames-only-mode version: 20190524.1439
* Operating system (and version): linux 5.6.7.arch1-1
* Window manager (and version): i3-gaps 4.18.1-1

**Comment by davidshepherd7** [comment]
Hi, this is a strange and interesting bug thanks for reporting it!

I think the issue is that deep down inside org in `org-compile-file` it uses `save-window-excursion` to prevent the DVI popup window from appearing, but the docs for that function state:

> BEWARE: Most uses of this macro introduce bugs.
> E.g. it should not be used to try and prevent some code from opening
> a new window, since that window may sometimes appear in another frame,
> in which case ‘save-window-excursion’ cannot help.

I've added `org-compile-file` to the list of functions which don't use frames, which should work around the issue. Can you grab the latest build (either directly from github, or from melpa unstable whenever it next builds) and see if it helps please?

**Comment by nettoyoussef** [comment]
Hi David!

Thanks for your fast response. 

Yes, indeed your fix avoided the window from opening in my machine :smiley:. From my point of view, you can close this issue. Thanks again for your time.

PS; I am kind of a new emacser. I had to install `quelpa` and `quelpa-use-package` to use the github version. This slowed things down a bit. Do you know how do I make them faster again? I tried adding:

```lisp
  (setq quelpa-update-melpa-p nil)
``` 
but there still some slowness. Maybe I should wait for this new version to go to Melpa and then just remove `quelpa` and `quelpa-use-package`? What do you think?

**Comment by davidshepherd7** [comment]
Great, thanks.

> PS; I am kind of a new emacser. I had to install quelpa and quelpa-use-package to use the github version. This slowed things down a bit. Do you know how do I make them faster again?

I haven't used quelpa, but [melpa has built the new version now](https://melpa.org/#/frames-only-mode) so yeah I would just switch back to that and remove quelpa.
