### ISSUE TITLE
Feature request: close magit-status frames

### ISSUE THREAD

**Issue by tuh8888** [davidshepherd7/frames-only-mode#33]
I'm often left with extra new frames after opening magit-status and doing something in the frame. Opening magit-status (opens a new frame), looking around (navigating hunks), then pressing `q` will kill the frame as desired. However, if I make a commit, or start a commit and then cancel, or other similar action, return to magit-status and press `q`, I am left with a frame that contains the window I opened magit-status from. 

This is due to `magit-bury-buffer-function` being set to `magit-restore-window-configuration`. So I recommend adding `(list 'magit-bury-buffer-function #'bury-buffer)` to `frames-only-mode-configuration-variables`. This closes the frame made to display magit-status as desired.

**Comment by tuh8888** [comment]
I forogot that I also had to add to get the magit-status fame to be killed as well.
```emacs-lisp
(add-hook 'magit-status-mode-hook (lambda () (add-to-list 'frames-only-mode-kill-frame-when-buffer-killed-buffer-list (buffer-name))))
```

Maybe a better solution is  `(list 'magit-bury-buffer-function #'delete-frame)`

**Comment by davidshepherd7** [comment]
Yes! This has been mildly annoying me for a long time but I never got around to looking into how to fix it. Thanks for doing the research :slightly_smiling_face:
