### ISSUE TITLE
Magit windows do not always open in a new frame, so current bury buffer function doesn't have the intended effect.

### ISSUE THREAD

**Issue by aardvark179** [davidshepherd7/frames-only-mode#34]
Although the main magic command will open a new frame, other commands such as `magic-log` do not open a new frame, so burying those buffers should not close the frame.

## Reproducing

Start magit, observe that it opens a new frame.
In the magit buffer bring up a log by doing something like `l` `b`, observe that this does not open a new frame.
Hit `q` to bury the buffer, and observe that the frame is deleted.

## Other useful info

* Emacs version: 27.1
* frames-only-mode version: 20200728.740
* Operating system (and version): Oracle Linux 7.6
* Window manager (and version): i3 4.12
* magit 20201004.830

**Comment by davidshepherd7** [comment]
Hi! Thanks for reporting this and making it easy to reproduce. This is fixed in master but let me know if you run into any similar issues :)
