### ISSUE TITLE
A recent magit version changed what magit-bury-buffer-function does

### ISSUE THREAD

**Issue by davidshepherd7** [davidshepherd7/frames-only-mode#35]
It now passes an argument to the function, which we need to ignore.

**Comment by freckletonj** [comment]
and the new default of `#'delete-frame` was surprising, and unnecessarily difficult to track down after a mass package update.

This is the fix, btw, if anyone else stumbles here:

```lisp
(setq magit-bury-buffer-function #'magit-restore-window-configuration)
```

**Comment by davidshepherd7** [comment]
Thanks for the extra information, this should be fixed in master (should land in melpa in a few hours). If you have a chance can you give it a try and let me know please?

More context for google: the error message is `magit-mode-bury-buffer: Wrong type argument: framep, kill`.

For completeness: that `setq` will be overwritten if `frames-only-mode` is toggled afterwards, you can also customise `frames-only-mode-configuration-variables` to remove/modify anything that it sets.
