### ISSUE TITLE
Installing f-o-m made no difference

### ISSUE THREAD

**Issue by NightH4nter** [davidshepherd7/frames-only-mode#36]
My actual init.el: https://gist.github.com/NightH4nter/3e3b13b6df1a9cc5f3cab09a072e7c8d#file-init-el.
No idea if it's me doing anything wrong. Yes, just switching to Emacs. Probably made a dumb mistake somewhere.

## Reproducing

1. Run emacs -Q
2. Put 
`(require 'package)`
`(setq package-load-list`
`'((frames-only-mode t)))`
`(package-initialize)`
into scratch buffer
3. `M-x eval-buffer`
4. Get this:
![image](https://user-images.githubusercontent.com/31319604/103240566-98810f80-4948-11eb-92bb-eeb7403c779f.png)
instead of what it's supposed to look like:
![image](https://user-images.githubusercontent.com/31319604/103240207-94082700-4947-11eb-9e09-001f35f21f97.png)

## Other useful info

* Emacs version: 26.1
* frames-only-mode version:  20200728.740
* Operating system (and version): Debian Buster
* Window manager (and version): AwesomeWM 4.3

**Comment by davidshepherd7** [comment]
Hi, welcome to Emacs!

You need to call the function `frames-only-mode` to enable it. Just add the
line `(frames-only-mode)` underneath the require.

**Comment by NightH4nter** [comment]
> Hi, welcome to Emacs! You need to call the function `frames-only-mode` to enable it. Just add the line `(frames-only-mode)` underneath the require.

Still doesn't work.
![image](https://user-images.githubusercontent.com/31319604/103286141-acc01d80-49d7-11eb-843e-dd4319970b3e.png)

Calling this function manually returned something like "frames-only-mode turned off".

**Comment by davidshepherd7** [comment]
> Calling this function manually (I mean, with M-x) returned something like "frames-only-mode turned off".

Mode functions toggles the mode when called interactively, so the first call (in your init file) will enable it but a second manual call will disable it. You can check if a mode is enabled by looking at the value of the variable with the same name (e.g. by running `describe-variable`).

> Still doesn't work.

Oh wait, I think I might have misunderstood, from the screenshot it looks like you have two Emacs frames open. Is your issue that the Emacs frames (a.k.a. OS windows) are not aligned properly? If so that has nothing to do with `frames-only-mode`, it's probably your window manager that controls the size and position.

**Comment by NightH4nter** [comment]
> Mode functions toggles the mode when called interactively, so the first call (in your init file) will enable it but a second manual call will disable it. You can check if a mode is enabled by looking at the value of the variable with the same name (e.g. by running describe-variable).

It was just me trying to figure out if the function was toggled.

> Oh wait, I think I might have misunderstood, from the screenshot it looks like you have two Emacs frames open. Is your issue that the Emacs frames (a.k.a. OS windows) are not aligned properly? If so that has nothing to do with frames-only-mode, it's probably your window manager that controls the size and position.

Right window on every screenshot is **not** Emacs. It's terminal with *something* running in it. My problem is that Emacs window can't fit it's tile, unless running in full screen. It has nothing to do with the WM itself, as no rules are applied to it in the config, so it's an issue with Emacs itself. I even tested it with BSPWM, and it somehow manages to ignore BSPWM's attempts to resize it to fit the layout.

**Comment by davidshepherd7** [comment]
Ok I think I understand the problem now. This doesn't seem to be related to `frames-only-mode`, all it does is configure Emacs to open new frames instead of Emacs windows (it has no impact on how those frames look etc).

If it's definitely not the window manager then the only other idea I have is to check the value of `default-frame-alist`. Other than that I can't help you, sorry.

**Comment by NightH4nter** [comment]
This is the output:
![image](https://user-images.githubusercontent.com/31319604/103375152-559e7380-4ad1-11eb-8a13-26b6401d12b9.png)
As text:
```
default-frame-alist is a variable defined in ‘C source code’.
Its value is nil

  This variable may be risky if used as a file-local variable.

Documentation:
Alist of default values for frame creation.
These may be set in your init file, like this:
  (setq default-frame-alist '((width . 80) (height . 55) (menu-bar-lines . 1)))
These override values given in window system configuration data,
 including X Windows’ defaults database.
For values specific to the first Emacs frame, see ‘initial-frame-alist’.
For window-system specific values, see ‘window-system-default-frame-alist’.
For values specific to the separate minibuffer frame, see
 ‘minibuffer-frame-alist’.
The ‘menu-bar-lines’ element of the list controls whether new frames
 have menu bars; ‘menu-bar-mode’ works by altering this element.
Setting this variable does not affect existing frames, only new ones.

You can customize this variable.

[back]
```

**Comment by NightH4nter** [comment]
Closing. Adding ```(setq frame-resize-pixelwise t)``` to init file seems to "fix" the issue.

Have to admit, although this program is quite old and quite popular *(laughs at Kakoune)*, it's quite painful to configure, because in order to fix a little kink, that comes from Emacs'es attempts to be an entire operating system, you really need to read through it's entire manual, and then... probably come up with an idea.
