### ISSUE TITLE
[bug] frames-only-mode doesn't work on gentoo + hyprland

### ISSUE THREAD

**Issue by FFFluoride** [davidshepherd7/frames-only-mode#40]
## Reproducing

Frames only mode doesn't open a new window when I split.
It's probably my [config](https://gist.github.com/FFFluoride/6fd0bdcb5c9b0759bfd60e453b565997) though.

## Other useful info

* Emacs version: 29.4
* frames-only-mode version: latest on melpa??
* Operating system (and version): Gentoo (portage version: 3.0.65 not really sure this is what you meant)
* Window manager (and version): Hyprland 0.42.0

Edit:
It seems that it works for `C-c C-'` buffer when that pops up but doesn't work for splitting the window

**Comment by davidshepherd7** [comment]
Hey, sorry I've only just got around to looking at this.

Yeah: this mode doesn't force functions which explicitly ask to split a window to use frames instead. It only only things that use `display-buffer` or similar, i.e. functions that are already intended to be agnostic about how the buffer is displayed.

**Comment by FFFluoride** [comment]
I actually caught the thing being merged by github. Was kind of wondering about that lol.
Anyway thank you for the change.
