### ISSUE TITLE
Consider converting into a "real" minor mode

### ISSUE THREAD

**Issue by davidshepherd7** [davidshepherd7/frames-only-mode#5]
That can be turned on/off with a command.

**Comment by davidshepherd7** [comment]
Closed by fb006c31b9189fb1d0ab19363ac0e0d59d579a3a

**Comment by davidshepherd7** [comment]
@spwhitton I think you were interested in this?

It's not necessarily all working yet (I want to use it for a few weeks before I publish it anywhere), but we're getting there :smile:.

**Comment by spwhitton** [comment]
On Sun, Oct 23, 2016 at 09:37:01AM -0700, David Shepherd wrote:
> @spwhitton I think you were interested in this?
> 
> It's not necessarily all working yet (I want to use it for a few weeks before I
> publish it anywhere), but we're getting there 😄.

Yes.  Thanks!

-- 
Sean Whitton
