### ISSUE TITLE
Publish to melpa

### ISSUE THREAD

**Issue by davidshepherd7** [davidshepherd7/frames-only-mode#6]
If you would like this to be on melpa please post in this thread.

The reason I'm not doing it yet is that it might be non-trivial to do. If I
just publish this as it is then merely installing the package would modify
settings which seems undesirable. Ideas?

**Comment by IvanMalison** [comment]
I'd love to see this on melpa!

> The reason I'm not doing it yet is that it might be non-trivial to do. If I
> just publish this as it is then merely installing the package would modify
> settings which seems undesirable. Ideas?

minor-mode?

**Comment by davidshepherd7** [comment]
Yeah someone else mentioned taking a look at doing this a few months ago but I guess they haven't had a chance.

I'll give it a go this weekend. Shouldn't be too difficult actually, I understand emacs a lot better now than when I first wrote this.

**Comment by IvanMalison** [comment]
Do you actually use this in your init? Are you still using xmonad? I tried playing around with it, and its definitely pretty close to what I want, but as someone who has never really used frames AT ALL before its taking some getting used to for me.

**Comment by davidshepherd7** [comment]
Yeah I've been using it every day for years, it works really well for me :)

**Comment by davidshepherd7** [comment]
Hi, I've turned it into a global minor mode, but I'm going to use it for a few weeks before I publish to melpa to try to iron out any bugs. Feel free to try out the current code and let me know if you have any problems.

Also there's no particular need to use XMonad, everything here should work equally well with any tiling window manager. I think I went with it because Haskell seemed cool :smile:.

**Comment by IvanMalison** [comment]
> Also there's no particular need to use XMonad, everything here should work equally well with any tiling window manager. I think I went with it because Haskell seemed cool .

Oh yeah, I'm aware, I just happen to be an xmonad user as well, so I was wondering about your usage patterns.

I've just gotten frustrated with having both emacs windows and xmonad tiles to deal with.

**Comment by spwhitton** [comment]
@davidshepherd7 When you consider the minor mode stable, please be sure to tag a release so that this ends up on MELPA stable, too.

**Comment by spwhitton** [comment]
On Thu, Oct 20, 2016 at 04:43:36PM -0700, Ivan Malison wrote:
> Do you actually use this in your init? Are you still using xmonad?

I do!

-- 
Sean Whitton

**Comment by davidshepherd7** [comment]
Done! https://melpa.org/#/frames-only-mode
